// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbdmgfxfsmjhdzlrwqju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiZG1nZnhmc21qaGR6bHJ3cWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTQ1ODgsImV4cCI6MjA2MTMzMDU4OH0.kQg6oVBm6xh9Sxe2Rv4ljDVuOM6urnbT8wqW45nvjV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);